export const CLOSE_INFO = 'CLOSE_INFO'
export const SHOW_INFO = 'SHOW_INFO'

export const ADD_POKEMON = 'ADD_POKEMON'
export const REMOVE_POKEMON = 'REMOVE_POKEMON'
export const CHANGE_POKEMON = 'CHANGE_POKEMON'
export const CREATE_POKEMON = 'CREATE_POKEMON'

export const SHOW_POPUP = 'SHOW_POPUP'
export const HIDE_POPUP = 'HIDE_POPUP'

export const POPUP_CREATE_POKEMON = 'POPUP_CREATE_POKEMON'
export const POPUP_INFO_POKEMON = 'POPUP_INFO_POKEMON'
