
//*** fake data ***//
export const users = [
	{id: 0, avatar: './public/avatars/arbok.png', name: 'Arbok', info: 'Арбок - это покемон-кобра фиолетового цвета. На животе причудливые узоры в виде глаз и рта. Они служат предупреждением для людей и других покемонов, что эрбок ядовит. Было найдено шесть вариаций узоров, они меняются в зависимости от места обитания покемона. По сравнению с прошлой эволюцией, арбок стал короче, но гораздо сильнее. Исчезла "погремушка" на конце хвоста.'},
	{id: 1, avatar: './public/avatars/beedrill.png', name: 'Beedrill', info: 'Бидрилл (англ. Beedrill) - покемон-пчела двойного (насекомое/ядовитый) типа. Живёт в лесах. Атакует своими жалами которых у неё целых 2 на лапках и 1 на брюшке. Самый мощный яд в жале на брюшке. Иногда встречаются в виде роя. Очень быстро летает. Побеждает жертву жалами и несёт в гнездо, чтобы когда-нибудь съесть. Иногда именуется осиллой. Эволюционирует из Какуны на 10 уровне. Финальная эволюция Видла. Живёт в лесах.'},
	{id: 2, avatar: './public/avatars/blastoise.png', name: 'Blastoise', info: 'Бластойз — это большая, синяя черепаха, ходящая на двух ногах. У него крепкий панцирь и две мощные водяные пушки, сделанными из материала, похожего на сталь, располагаются они на верхней части панциря с разных сторон. Бластойз может втянуть их внутрь или повернуть назад, чтобы струя помогала ему давить противников. Голова Бластойза крепкая и прочная, что позволяет ему таранить врагов в битве. В этом ему еще помогают треугольные уши, которые он выставляет вперед, используя как рога. На его толстых и бороздчатых руках по три когтя. Белое кольцо вокруг панциря окружает и его плечи. В отличие от Сквиртла и Вартортла хвост Бластойза синий и короткий.'},
	{id: 3, avatar: './public/avatars/charizard.png', name: 'Charizard', info: 'Чаризард значительно отличается от своих эволюций. У него появились крылья, благодаря которым он может свободно летать. Также у Чаризарда вытянулась шея и удлинился хвост. Теперь у него более вытянутая морда. На голове два рога, плюс по рогу на каждом крыле. На лапах по три когтя. Внешне Чаризард очень похож на драконов из западной мифологии. У Чаризарда светло-красная или оранжевая шкура, брюхо кремового цвета. Изнутри крылья у него тёмно-голубого цвета. Чаризард — единственный стартовик с такой особенностью. На конце хвоста у него горит пламя, по размеру которого можно судить о силе и здоровье чаризарда. Чаризард и его предэволюции — единственные покемоны, для которых пламя является частью тела, которое невозможно потушить, не причинив вреда покемону.'},
	{id: 4, avatar: './public/avatars/dewgong.png', name: 'Dewgong', info: 'Dewgong is a pinniped Pokémon resembling a sea lion. It has a snowy white, furry body, which renders it virtually invisible in snowy conditions. Its face has two black eyes with no visible sclerae, a black button nose and two tusks extending from its upper jaw. It has a streamlined body with two front flippers and a long flowing tail. Even in extremely cold and ice-packed waters, its tail allows it to be a swift and agile swimmer at speeds of 8 knots. On top of its head is a sharp horn, which allows it to cut and plow through even the thickest of ice floes.'},
	{id: 5, avatar: './public/avatars/drowzee.png', name: 'Drowzee', info: 'Drowzee is a bipedal Pokémon that resembles a tapir. It has tired-looking eyes, a short trunk above its mouth, and triangular ears. The upper half of Drowzees body is yellow and the lower half is brown. A wavy line separates the two halves. It has a round belly and short legs. Its feet are brown, except for its two toes, which are the same yellow as the upper half of the body. The bottom of each foot has a small, round, pink pad in the middle of it. There are three fingers on each of its hands.'},
	{id: 6, avatar: './public/avatars/fearow.png', name: 'Fearow', info: 'Фоновое оперение фироу — коричневое, оперение кончиков крыльев — бежевое, хохолок на голове — красный, клюв и ноги — розовые.'},
	{id: 7, avatar: './public/avatars/golem.png', name: 'Golem', info: 'Golem is a bipedal tortoise-like Pokémon with plated, green rocks as its shell. Golem grows bigger by shedding its skin once a year.'},
	{id: 8, avatar: './public/avatars/nidoking.png', name: 'Nidoking', info: 'Нидокинг — большой мощный двуногий покемон фиолетового цвета. У него очень большие рога и уши. Так же имеет большие когти — по одному на нижних конечностях и по три на верхних.'},
	{id: 9, avatar: './public/avatars/nidoqueen.png', name: 'Nidoqueen', info: 'Nidoqueen is a large, bipedal blue Pokémon with distinct reptilian features. Its body is encased with extremely hard scales that serve as excellent protection from any attack and stand up when Nidoqueen is excited or provoked. It has a blunt snout, narrow brown eyes, and large ears with brown insides. There is a small horn on its forehead, and single spine on each ear, and there is a line of toxic spikes running down the length of its back.'},
	{id: 10, avatar: './public/avatars/parasect.png', name: 'Parasect', info: 'Парасект, как и его предварительная эволюция парас, похож на краба. У него есть большой, красный с оранжевыми пятнами гриб на спине и шесть конечностей. Две передние конечность парасекта похожи на клешни.'},
	{id: 11, avatar: './public/avatars/pidgeotto.png', name: 'Pidgeotto', info: 'покемон двойного (нормальный/летающий) типа. Живёт на огромной территории в центре которой располагается гнездо. Имеет острые когти и острое зрение. Постоянно патрулирует свою территорию и безжалостно наказывает острыми когтями всех непрошенных гостей. Очень энергичный '},
	{id: 12, avatar: './public/avatars/poliwrath.png', name: 'Poliwrath', info: 'Поливрат – крупная и весьма мускулистая лягушка синего цвета, передвигающаяся на задних лапах. Имеет округлое тело, достаточно длинные лапы и рисунок на животе, изображающий большую чёрную спираль. В отличие от своих предыдущих форм, на передних лапах покемона появилось подобие пальцев.'},
	{id: 13, avatar: './public/avatars/raichu.png', name: 'Raichu', info: 'В отличии от "классической" версии у этого вида более округлённые хвост и уши. Кроме того, алольский райчу насыщенного карамельного цвета и имеет голубые глаза.'},
	{id: 14, avatar: './public/avatars/raticate.png', name: 'Raticate', info: 'Ратикэйт - покемон-крыса. Шерсть у него в основном коричневого цвета, лишь чуть светлее она на брюхе. Лапки короткие, с тремя когтистыми пальчиками; хвост, как у его прообраза - крысы, длинный и не покрыт шерстью. На голове расположены глаза, уши, нос, усы и рот с большими резцами, характерными для грызунов'},
	{id: 15, avatar: './public/avatars/sandslash.png', name: 'Sandslash', info: 'Сэндслэш — большой панголин. Его шкура на спине — это большие шипы коричневого цвета. Он может свернуться в большой шар, чтобы защитить свое подбрюшье, а также, в этом положении он может катится и атаковать своими шипами. '},
	{id: 16, avatar: './public/avatars/venonat.png', name: 'Venonat', info: 'Венонат похож на мячик, который покрыт большим, фиолетовым мехом. У него пара ножек, похожих на башмачки, и короткие передние лапки. Рот веноната похож на клещи. Наиболее примечательной особенностью Венонатов являются их большие, красные глаза. Они также имеют небольшой нос только под их ними глазами'},
	{id: 17, avatar: './public/avatars/venusaur.png', name: 'Venusaur', info: 'покемон двойного травяного/ядовитого типа из первого поколения покемонов. На 32 уровне эволюционирует из ивизавра. Финальная эволюция травяного стартовика бульбазавра. Развивается в Мега Венузавра с помощью камня Венусарита.'},
	{id: 18, avatar: './public/avatars/vileplume.png', name: 'Vileplume', info: 'Vileplume is a blue, bipedal Pokémon with rudimentary hands and feet. It has beady red eyes and a massive red flower growing from its head. Vileplumes flower is said to have the largest petals in the world, and is almost too heavy for the Pokémon itself to support. The rounded petals of the flower are red and covered with white spots'},
]